### PR TITLE
Sticky Notification and Dashboard

### PR DESCRIPTION
**Pull request by Mantus667**
Added a sticky notification when someone is editing the viewed content node for more visual reminder.

Added a simple dashboard to see which user is editing which content node

### CODE REVIEW

**Comment by TimGeyssens** [comment]
Woot that's fast will review on monday but from what I can see it looks really good!

**Comment by Mantus667** [comment]
Yeah had some time yesterday. :)
Have some more ideas for the dashboard for a better look&feel but one step after another. :+1:

**Comment by TimGeyssens** [comment]
Would be nice if it also shows edits in realtime :) (so no refresh needed to see changes)

**Comment by Mantus667** [comment]
Yes thats right. Also thought to integrate it but currently "arguing" with my uaas website -.-

**Pull request merged**
